apiVersion: example.com/v1
kind: Manifest
spec:
  schemaObject:
    $schema: https://json-schema.org/draft/2020-12/schema
    type: object
    required:
      - id
    properties:
      id:
        type: string
      quantity:
        type: integer
